### ISSUE TITLE
Documentation Review

### ISSUE THREAD

**Issue by jmeyer90** [leocho1989/leel#1]
# MVP
1. Specifically mention CRUD functionality for leels.

# Schema
1. List associations as bullet points under the corresponding table.

# Sample State
1. Looks great!

# Back-End Routes
1.  GET /api/leels/:leel_id/replies create a new reply on a leel- This should be a POST instead of GET

# Front-End Routes & Components
1. Looks great!

**Comment by leocho1989** [comment]
Fixed (Logged in users can use website features, such as post leels, read leels, update leels, delete leels, edit profile, search information etc.). for MVP list.
Added associations as bullet points.
Fixed route for creating a reply.
Thanks
