### ISSUE TITLE
Finished mvp part 1

### ISSUE THREAD

**Issue by leocho1989** [leocho1989/leel#2]
Finished mvp part 1, login and signup authentication. Please help review it! 
https://leels.herokuapp.com/#/

username:test, password:testtest

**Comment by jmeyer90** [comment]
Auth Review:

- When logged in, we should have our username and logout button styled.
- We should style our forms to most closely resemble the forms on Tumblr. In your case, this mostly means larger, more readable font. Make sure your zoom is set to 100% in the browser.

**Comment by leocho1989** [comment]
Fixed the page display size issue and styled login username on nav bar. Thanks!
