### ISSUE TITLE
MVP 2- Posts finished

### ISSUE THREAD

**Issue by leocho1989** [leocho1989/leel#3]
Finished mvp 2, Posts. Please help review it!
https://leels.herokuapp.com/#/

username:test, password:testtest

**Comment by jmeyer90** [comment]
Posts MVP Review:

* For uploading an image, a user should have optional drag and drop functionality.
* For submitting a quote, there should be two separate input fields: one for the quote, another for the source. They should be styled to match the Tumblr quote form.
* For all of the textareas on our forms, we should remove the resizing option at the bottom right of the textarea.
* When trying to scroll through the page, the mouse has to be over a very specific are to work. This gives a bad UI and makes users think they can't scroll through the page. This can be changed by manipulating the posts index container, or some similar html element, to take up the full width of the page.

**Comment by leocho1989** [comment]
Hi,justin, I finished all the above issues.  For the drag and drop feature for uploading, users can drag and drop pic files to the upload button area, tested, it works, so I added a sentence below it.  Thanks!

**Comment by jmeyer90** [comment]
Everything looks good! Please move on to your next MVP.
