### ISSUE TITLE
MVP 3 likes finished

### ISSUE THREAD

**Issue by leocho1989** [leocho1989/leel#4]
Finished mvp 3, likes. Please help review it!
https://leels.herokuapp.com/#/

username:test, password:testtest

**Comment by jmeyer90** [comment]
Likes MVP Review:

* In the user drop-down, we have the "Likes" option to click. This should bring us to an index page of liked items. We must implement this functionality before the MVP is completed.

**Comment by leocho1989** [comment]
Hi, Justin, I added likes show page. Please review it. Thanks

**Comment by jmeyer90** [comment]
Everything looks good! Please move on to your next MVP.
